# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  phpVersion: 7.2

steps:
script:
- apt-get update && apt-get install -y unzip
- curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
- apt-get -qq install git-ftp
- git ftp push --user:pj1987 --passwd:d]T#&.xO3$J2 ftp://45.120.149.56/public_html/demo.vthinksolution.com/wordpress